version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: diazero-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: diazero_api
    ports:
      - "3306:3306"
    cap_add:
      - SYS_NICE
  
  app:
    image: romaol7/diazero:V1
    container_name: diazero_app
    depends_on:
      - mysql-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/diazero_api
    ports:
      - "9090:8080" #host:container